### ISSUE TITLE
Migrate to ESLint v2

### ISSUE THREAD

**Issue by intih** [bbc/kandl-style-guide#26]
ESLint v2.0.0 is out. We should consider migrating (using the guide @ http://eslint.org/docs/user-guide/migrating-to-2.0.0)

**Comment by djorak** [comment]
Used v2.1.0 in bbc/morph-bitesize-decks-list, only change I had to make was to convert and rename the config file to `.eslintrc.json` (not using a file extension is deprecated) and change the rule `space-after-keywords: [2, "always"],` to `"keyword-spacing": 2,`.

**Comment by intih** [comment]
Config now uses ESLint v2; see https://github.com/bbc/kandl-eslint-config
